/**
 * Point-splitting mathematics.
 *
 * Business rule
 * -------------
 *   palletPoints = cartons x product.pointValue
 *   each currently-active team member receives palletPoints / memberCount
 *
 * Money-grade exactness
 * ---------------------
 * Floating point division would let `sum(shares) !== palletPoints` (e.g. 100 / 3).
 * We therefore do the whole computation in integer **milli-points**
 * (1 point = 1000 milli-points), hand out the remainder one milli-point at a
 * time to the earliest members, and only convert back to a float at the very
 * end. The invariant `sum(result.shares) === result.totalPoints` always holds
 * (up to the 3-decimal rounding of a single point).
 */

export const MILLI = 1000;

export interface PointSplitResult {
  /** Total points generated by the pallet. */
  totalPoints: number;
  /** Points credited to each member, in the same order as `memberIds`. */
  shares: number[];
  /** Per-member breakdown, ready to be persisted as point_award rows. */
  awards: Array<{ workerId: string; points: number }>;
}

export function computePalletPoints(cartons: number, pointValue: number): number {
  return roundPoints(cartons * pointValue);
}

/** Round to 3 decimals without binary floating point drift. */
export function roundPoints(value: number): number {
  return Math.round(value * MILLI) / MILLI;
}

export function toMilli(points: number): number {
  return Math.round(points * MILLI);
}

export function fromMilli(milli: number): number {
  return milli / MILLI;
}

/**
 * Split `totalPoints` across `memberIds`.
 *
 * @param memberIds Members active at the instant the pallet is logged. The
 *                  order is preserved and used to decide who receives the
 *                  remainder milli-points (earliest first, by joinedAt).
 * @param totalPoints Total points to distribute. Defaults to
 *                  `cartons x pointValue`.
 */
export function splitPoints(
  cartons: number,
  pointValue: number,
  memberIds: string[],
  totalPointsOverride?: number,
): PointSplitResult {
  const totalPoints = roundPoints(
    totalPointsOverride !== undefined ? totalPointsOverride : computePalletPoints(cartons, pointValue),
  );

  if (memberIds.length === 0) {
    // Defensive: a batch must always have at least one member. Callers validate
    // before reaching this point, but returning a zero split keeps the ledger
    // consistent instead of throwing inside a transaction.
    return { totalPoints, shares: [], awards: [] };
  }

  const totalMilli = toMilli(totalPoints);
  const count = memberIds.length;
  const base = Math.trunc(totalMilli / count);
  let remainder = totalMilli - base * count;

  const sharesMilli = memberIds.map(() => base);
  for (let i = 0; i < count && remainder > 0; i += 1) {
    sharesMilli[i] += 1;
    remainder -= 1;
  }

  const shares = sharesMilli.map(fromMilli);
  const awards = memberIds.map((workerId, index) => ({
    workerId,
    points: shares[index],
  }));

  return { totalPoints, shares, awards };
}

/** Sum helper that keeps the ledger total stable to 3 decimals. */
export function sumPoints(values: number[]): number {
  return fromMilli(values.reduce((sum, value) => sum + toMilli(value), 0));
}

/** Points per active hour. Returns 0 for a zero/negative denominator. */
export function pointsPerHour(points: number, activeSeconds: number): number {
  if (activeSeconds <= 0) return 0;
  return roundPoints(points / (activeSeconds / 3600));
}
