/**
 * LocalRepository — zero-configuration persistence adapter.
 *
 * Backs the entire platform with a single JSON document on disk
 * (`.data/shift-db.json` by default). This is what makes the project runnable
 * with `npm run dev` and no cloud account whatsoever, and it is what the
 * automated tests exercise.
 *
 * Design notes
 * ------------
 * - The whole document is loaded once per process and cached on `globalThis`
 *   so Next.js hot reloads do not lose state.
 * - Mutations are serialised through a promise queue: two concurrent HTTP
 *   requests can never interleave a read-modify-write cycle.
 * - Writes are atomic (`write temp -> rename`) so a crash mid-save cannot
 *   corrupt the store.
 * - A document written by an older schema version is discarded rather than
 *   migrated. It is demo data, and discarding it re-triggers the automatic
 *   seed, which is exactly the desired behaviour after a schema change.
 * - If the filesystem is read-only (serverless), the adapter degrades to a
 *   purely in-memory store and logs a warning instead of throwing. Production
 *   deployments are expected to set `DATABASE_URL`.
 */

import { mkdirSync, readFileSync, renameSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, isAbsolute, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';

import type {
  AppSetting,
  Batch,
  BatchMember,
  PalletLog,
  PalletSize,
  PauseLog,
  PointAward,
  Product,
  ProductionLine,
  Race,
  RaceProductPoint,
  Worker,
} from '@/lib/domain/types';
import type {
  BatchFilter,
  PalletLogFilter,
  PalletWithAwards,
  PointAwardFilter,
  RaceFilter,
  Repository,
} from '@/lib/repo/types';
import { RepositoryError } from '@/lib/repo/types';

interface LocalDatabaseShape {
  version: number;
  workers: Worker[];
  productionLines: ProductionLine[];
  products: Product[];
  palletSizes: PalletSize[];
  races: Race[];
  raceProductPoints: RaceProductPoint[];
  batches: Batch[];
  batchMembers: BatchMember[];
  palletLogs: PalletLog[];
  pointAwards: PointAward[];
  pauseLogs: PauseLog[];
  appSettings: AppSetting[];
}

/**
 * Bump whenever the document shape changes. A stored document with a different
 * version is discarded and regenerated by `lib/bootstrap.ts`.
 *
 * v3 — concurrent-race scoring: race attribution moved entirely onto
 *      `pointAwards` (one row per worker × active race); `batches.raceId` and
 *      `palletLogs.raceId` were removed, as was `races.templateOf`.
 */
const SCHEMA_VERSION = 3;

function emptyDatabase(): LocalDatabaseShape {
  return {
    version: SCHEMA_VERSION,
    workers: [],
    productionLines: [],
    products: [],
    palletSizes: [],
    races: [],
    raceProductPoints: [],
    batches: [],
    batchMembers: [],
    palletLogs: [],
    pointAwards: [],
    pauseLogs: [],
    appSettings: [],
  };
}

function storePath(): string {
  const configured = process.env.SHIFT_LOCAL_STORE_PATH?.trim() || '.data/shift-db.json';
  return isAbsolute(configured) ? configured : resolve(process.cwd(), configured);
}

interface LocalStoreGlobal {
  __shiftLocalDb?: LocalDatabaseShape;
  __shiftLocalQueue?: Promise<unknown>;
  __shiftLocalWritable?: boolean;
}

const globals = globalThis as unknown as LocalStoreGlobal;

function loadFromDisk(): LocalDatabaseShape {
  const path = storePath();
  if (!existsSync(path)) return emptyDatabase();

  try {
    const raw = readFileSync(path, 'utf8');
    if (!raw.trim()) return emptyDatabase();

    const parsed = JSON.parse(raw) as Partial<LocalDatabaseShape>;

    if ((parsed.version ?? 0) !== SCHEMA_VERSION) {
      console.info(
        `[shift] Local store schema v${parsed.version ?? 0} does not match v${SCHEMA_VERSION}; ` +
          'starting fresh and regenerating the demo dataset.',
      );
      return emptyDatabase();
    }

    const base = emptyDatabase();
    return {
      version: SCHEMA_VERSION,
      workers: parsed.workers ?? base.workers,
      productionLines: parsed.productionLines ?? base.productionLines,
      products: parsed.products ?? base.products,
      palletSizes: parsed.palletSizes ?? base.palletSizes,
      races: parsed.races ?? base.races,
      raceProductPoints: parsed.raceProductPoints ?? base.raceProductPoints,
      batches: parsed.batches ?? base.batches,
      batchMembers: parsed.batchMembers ?? base.batchMembers,
      palletLogs: parsed.palletLogs ?? base.palletLogs,
      pointAwards: parsed.pointAwards ?? base.pointAwards,
      pauseLogs: parsed.pauseLogs ?? base.pauseLogs,
      appSettings: parsed.appSettings ?? base.appSettings,
    };
  } catch (error) {
    console.error('[shift] Failed to read local store, starting from an empty database.', error);
    return emptyDatabase();
  }
}

function getDb(): LocalDatabaseShape {
  if (!globals.__shiftLocalDb) {
    globals.__shiftLocalDb = loadFromDisk();
  }
  return globals.__shiftLocalDb;
}

function persist(): void {
  if (globals.__shiftLocalWritable === false) return;
  const path = storePath();
  try {
    mkdirSync(dirname(path), { recursive: true });
    const temp = `${path}.${process.pid}.tmp`;
    writeFileSync(temp, JSON.stringify(getDb(), null, 2), 'utf8');
    renameSync(temp, path);
    globals.__shiftLocalWritable = true;
  } catch (error) {
    globals.__shiftLocalWritable = false;
    console.warn(
      `[shift] Local store at "${path}" is not writable. Falling back to in-memory mode for this process. ` +
        'Set DATABASE_URL for durable production storage.',
      error,
    );
  }
}

/** Serialises every mutation. Callers get the value returned by `mutator`. */
function mutate<T>(mutator: (db: LocalDatabaseShape) => T): Promise<T> {
  const previous = globals.__shiftLocalQueue ?? Promise.resolve();
  const next = previous
    .catch(() => undefined)
    .then(() => {
      const result = mutator(getDb());
      persist();
      return result;
    });
  globals.__shiftLocalQueue = next.catch(() => undefined);
  return next;
}

function nowIso(): string {
  return new Date().toISOString();
}

export function newId(): string {
  return randomUUID();
}

function clone<T>(value: T): T {
  return structuredClone(value);
}

function inRange(value: string, from?: string, to?: string): boolean {
  const time = new Date(value).getTime();
  if (from && time < new Date(from).getTime()) return false;
  if (to && time >= new Date(to).getTime()) return false;
  return true;
}

export class LocalRepository implements Repository {
  readonly kind = 'local' as const;

  describe(): string {
    return `Local JSON store (${storePath()})`;
  }

  /* ------------------------------------------------------------- workers */

  async listWorkers(): Promise<Worker[]> {
    return clone(getDb().workers).sort((a, b) => a.fullName.localeCompare(b.fullName, 'he'));
  }

  async getWorkerById(id: string): Promise<Worker | null> {
    return clone(getDb().workers.find((worker) => worker.id === id) ?? null);
  }

  async getWorkerByEmployeeId(employeeId: string): Promise<Worker | null> {
    const needle = employeeId.trim().toLowerCase();
    return clone(
      getDb().workers.find((worker) => worker.employeeId.trim().toLowerCase() === needle) ?? null,
    );
  }

  async getWorkerByEmoji(emoji: string): Promise<Worker | null> {
    const needle = emoji.trim();
    return clone(getDb().workers.find((worker) => worker.emoji.trim() === needle) ?? null);
  }

  async insertWorker(worker: Worker): Promise<Worker> {
    return mutate((db) => {
      db.workers.push(worker);
      return clone(worker);
    });
  }

  async updateWorker(id: string, patch: Partial<Omit<Worker, 'id' | 'createdAt'>>): Promise<Worker> {
    return mutate((db) => {
      const index = db.workers.findIndex((worker) => worker.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Worker not found', 404);
      db.workers[index] = { ...db.workers[index], ...patch, id };
      return clone(db.workers[index]);
    });
  }

  async deleteWorker(id: string): Promise<void> {
    await mutate((db) => {
      db.workers = db.workers.filter((worker) => worker.id !== id);
    });
  }

  /* --------------------------------------------------- production lines */

  async listProductionLines(): Promise<ProductionLine[]> {
    return clone(getDb().productionLines).sort(
      (a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name, 'he'),
    );
  }

  async getProductionLineById(id: string): Promise<ProductionLine | null> {
    return clone(getDb().productionLines.find((line) => line.id === id) ?? null);
  }

  async getProductionLineByCode(code: string): Promise<ProductionLine | null> {
    const needle = code.trim().toLowerCase();
    return clone(
      getDb().productionLines.find((line) => line.code.trim().toLowerCase() === needle) ?? null,
    );
  }

  async insertProductionLine(line: ProductionLine): Promise<ProductionLine> {
    return mutate((db) => {
      db.productionLines.push(line);
      return clone(line);
    });
  }

  async updateProductionLine(
    id: string,
    patch: Partial<Omit<ProductionLine, 'id' | 'createdAt'>>,
  ): Promise<ProductionLine> {
    return mutate((db) => {
      const index = db.productionLines.findIndex((line) => line.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Production line not found', 404);
      db.productionLines[index] = { ...db.productionLines[index], ...patch, id };
      return clone(db.productionLines[index]);
    });
  }

  async deleteProductionLine(id: string): Promise<void> {
    await mutate((db) => {
      db.productionLines = db.productionLines.filter((line) => line.id !== id);
    });
  }

  /* ------------------------------------------------------------ products */

  async listProducts(): Promise<Product[]> {
    return clone(getDb().products).sort((a, b) => a.name.localeCompare(b.name, 'he'));
  }

  async getProductById(id: string): Promise<Product | null> {
    return clone(getDb().products.find((product) => product.id === id) ?? null);
  }

  async insertProduct(product: Product): Promise<Product> {
    return mutate((db) => {
      db.products.push(product);
      return clone(product);
    });
  }

  async updateProduct(id: string, patch: Partial<Omit<Product, 'id' | 'createdAt'>>): Promise<Product> {
    return mutate((db) => {
      const index = db.products.findIndex((product) => product.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Product not found', 404);
      db.products[index] = { ...db.products[index], ...patch, id };
      return clone(db.products[index]);
    });
  }

  async deleteProduct(id: string): Promise<void> {
    await mutate((db) => {
      db.products = db.products.filter((product) => product.id !== id);
      db.palletSizes = db.palletSizes.filter((size) => size.productId !== id);
      db.raceProductPoints = db.raceProductPoints.filter((row) => row.productId !== id);
    });
  }

  /* -------------------------------------------------------- pallet sizes */

  async listPalletSizes(): Promise<PalletSize[]> {
    return clone(getDb().palletSizes).sort((a, b) => a.sortOrder - b.sortOrder);
  }

  async listPalletSizesByProduct(productId: string): Promise<PalletSize[]> {
    return clone(
      getDb()
        .palletSizes.filter((size) => size.productId === productId)
        .sort((a, b) => a.sortOrder - b.sortOrder || a.cartons - b.cartons),
    );
  }

  async getPalletSizeById(id: string): Promise<PalletSize | null> {
    return clone(getDb().palletSizes.find((size) => size.id === id) ?? null);
  }

  async insertPalletSize(size: PalletSize): Promise<PalletSize> {
    return mutate((db) => {
      db.palletSizes.push(size);
      return clone(size);
    });
  }

  async updatePalletSize(id: string, patch: Partial<Omit<PalletSize, 'id' | 'productId'>>): Promise<PalletSize> {
    return mutate((db) => {
      const index = db.palletSizes.findIndex((size) => size.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Pallet size not found', 404);
      db.palletSizes[index] = { ...db.palletSizes[index], ...patch, id };
      return clone(db.palletSizes[index]);
    });
  }

  async deletePalletSize(id: string): Promise<void> {
    await mutate((db) => {
      db.palletSizes = db.palletSizes.filter((size) => size.id !== id);
    });
  }

  async deletePalletSizesByProduct(productId: string): Promise<void> {
    await mutate((db) => {
      db.palletSizes = db.palletSizes.filter((size) => size.productId !== productId);
    });
  }

  /* --------------------------------------------------------------- races */

  async listRaces(filter?: RaceFilter): Promise<Race[]> {
    let races = clone(getDb().races);
    if (filter?.status) races = races.filter((race) => race.status === filter.status);
    if (filter?.isPrimary !== undefined) races = races.filter((race) => race.isPrimary === filter.isPrimary);
    return races.sort((a, b) => new Date(b.startAt).getTime() - new Date(a.startAt).getTime());
  }

  async getRaceById(id: string): Promise<Race | null> {
    return clone(getDb().races.find((race) => race.id === id) ?? null);
  }

  async getPrimaryRace(): Promise<Race | null> {
    const race = getDb()
      .races.filter((candidate) => candidate.status === 'ACTIVE' && candidate.isPrimary)
      .sort((a, b) => new Date(b.startAt).getTime() - new Date(a.startAt).getTime())[0];
    return clone(race ?? null);
  }

  async insertRace(race: Race): Promise<Race> {
    return mutate((db) => {
      db.races.push(race);
      return clone(race);
    });
  }

  async updateRace(id: string, patch: Partial<Omit<Race, 'id' | 'createdAt'>>): Promise<Race> {
    return mutate((db) => {
      const index = db.races.findIndex((race) => race.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Race not found', 404);
      db.races[index] = { ...db.races[index], ...patch, id };
      return clone(db.races[index]);
    });
  }

  async setPrimaryRace(id: string): Promise<Race | null> {
    return mutate((db) => {
      const target = db.races.find((race) => race.id === id);
      if (!target) throw new RepositoryError('not_found', 'Race not found', 404);

      db.races = db.races.map((race) => {
        if (race.id === id) return { ...race, isPrimary: true };
        // Only an ACTIVE race can hold the flag, so stale flags are cleared too.
        return race.isPrimary ? { ...race, isPrimary: false } : race;
      });

      return clone(db.races.find((race) => race.id === id) ?? null);
    });
  }

  async clearPrimaryRace(): Promise<void> {
    await mutate((db) => {
      db.races = db.races.map((race) => (race.isPrimary ? { ...race, isPrimary: false } : race));
    });
  }

  /**
   * Removes a race together with its own ledger rows, mirroring the
   * `ON DELETE CASCADE` on `point_awards.race_id`. No other race, batch or
   * pallet is touched — race attribution exists only in the award rows.
   */
  async deleteRace(id: string): Promise<void> {
    await mutate((db) => {
      db.races = db.races.filter((race) => race.id !== id);
      db.pointAwards = db.pointAwards.filter((award) => award.raceId !== id);
      db.raceProductPoints = db.raceProductPoints.filter((row) => row.raceId !== id);
    });
  }

  async listExpiredActiveRaces(now: string): Promise<Race[]> {
    const threshold = new Date(now).getTime();
    return clone(
      getDb().races.filter(
        (race) =>
          race.status === 'ACTIVE' && race.endAt !== null && new Date(race.endAt).getTime() <= threshold,
      ),
    );
  }

  /* --------------------------------------------------- race point values */

  async listRaceProductPoints(raceId?: string): Promise<RaceProductPoint[]> {
    const rows = clone(getDb().raceProductPoints);
    return raceId ? rows.filter((row) => row.raceId === raceId) : rows;
  }

  async insertRaceProductPoint(row: RaceProductPoint): Promise<RaceProductPoint> {
    return mutate((db) => {
      db.raceProductPoints.push(row);
      return clone(row);
    });
  }

  async updateRaceProductPoint(
    id: string,
    patch: Partial<Omit<RaceProductPoint, 'id'>>,
  ): Promise<RaceProductPoint> {
    return mutate((db) => {
      const index = db.raceProductPoints.findIndex((row) => row.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Race product point not found', 404);
      db.raceProductPoints[index] = { ...db.raceProductPoints[index], ...patch, id };
      return clone(db.raceProductPoints[index]);
    });
  }

  async deleteRaceProductPointsByRace(raceId: string): Promise<void> {
    await mutate((db) => {
      db.raceProductPoints = db.raceProductPoints.filter((row) => row.raceId !== raceId);
    });
  }

  async deleteRaceProductPoint(id: string): Promise<void> {
    await mutate((db) => {
      db.raceProductPoints = db.raceProductPoints.filter((row) => row.id !== id);
    });
  }

  /* ------------------------------------------------------------- batches */

  async listBatches(filter?: BatchFilter): Promise<Batch[]> {
    let batches = clone(getDb().batches);

    if (filter?.status) batches = batches.filter((batch) => batch.status === filter.status);
    if (filter?.lineId) batches = batches.filter((batch) => batch.lineId === filter.lineId);
    if (filter?.productId) batches = batches.filter((batch) => batch.productId === filter.productId);
    if (filter?.from || filter?.to) {
      batches = batches.filter((batch) => inRange(batch.startedAt, filter.from, filter.to));
    }

    batches.sort((a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime());
    if (filter?.limit && filter.limit > 0) batches = batches.slice(0, filter.limit);
    return batches;
  }

  async getBatchById(id: string): Promise<Batch | null> {
    return clone(getDb().batches.find((batch) => batch.id === id) ?? null);
  }

  async getActiveBatchByLine(lineId: string): Promise<Batch | null> {
    return clone(
      getDb().batches.find((batch) => batch.lineId === lineId && batch.status === 'ACTIVE') ?? null,
    );
  }

  async listActiveBatches(): Promise<Batch[]> {
    return clone(getDb().batches.filter((batch) => batch.status === 'ACTIVE'));
  }

  async insertBatch(batch: Batch): Promise<Batch> {
    return mutate((db) => {
      db.batches.push(batch);
      return clone(batch);
    });
  }

  async updateBatch(id: string, patch: Partial<Omit<Batch, 'id' | 'createdAt'>>): Promise<Batch> {
    return mutate((db) => {
      const index = db.batches.findIndex((batch) => batch.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Batch not found', 404);
      db.batches[index] = { ...db.batches[index], ...patch, id };
      return clone(db.batches[index]);
    });
  }

  async deleteBatch(id: string): Promise<void> {
    await mutate((db) => {
      db.batches = db.batches.filter((batch) => batch.id !== id);
      db.batchMembers = db.batchMembers.filter((member) => member.batchId !== id);
      db.palletLogs = db.palletLogs.filter((pallet) => pallet.batchId !== id);
      db.pointAwards = db.pointAwards.filter((award) => award.batchId !== id);
      db.pauseLogs = db.pauseLogs.filter((pause) => pause.batchId !== id);
    });
  }

  /* ------------------------------------------------------- batch members */

  async listBatchMembers(batchId: string): Promise<BatchMember[]> {
    return clone(getDb().batchMembers.filter((member) => member.batchId === batchId));
  }

  async listBatchMembersForBatches(batchIds: string[]): Promise<BatchMember[]> {
    const set = new Set(batchIds);
    return clone(getDb().batchMembers.filter((member) => set.has(member.batchId)));
  }

  async insertBatchMember(member: BatchMember): Promise<BatchMember> {
    return mutate((db) => {
      db.batchMembers.push(member);
      return clone(member);
    });
  }

  async updateBatchMember(
    id: string,
    patch: Partial<Omit<BatchMember, 'id' | 'batchId' | 'workerId'>>,
  ): Promise<BatchMember> {
    return mutate((db) => {
      const index = db.batchMembers.findIndex((member) => member.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Batch member not found', 404);
      db.batchMembers[index] = { ...db.batchMembers[index], ...patch, id };
      return clone(db.batchMembers[index]);
    });
  }

  /* --------------------------------------------------------- pallet logs */

  async listPalletLogsByBatch(batchId: string): Promise<PalletLog[]> {
    return clone(getDb().palletLogs.filter((pallet) => pallet.batchId === batchId));
  }

  async listPalletLogsForBatches(batchIds: string[]): Promise<PalletLog[]> {
    const set = new Set(batchIds);
    return clone(getDb().palletLogs.filter((pallet) => set.has(pallet.batchId)));
  }

  async listPalletLogsByIds(ids: string[]): Promise<PalletLog[]> {
    const set = new Set(ids);
    return clone(getDb().palletLogs.filter((pallet) => set.has(pallet.id)));
  }

  async listPalletLogs(filter?: PalletLogFilter): Promise<PalletLog[]> {
    let pallets = clone(getDb().palletLogs);

    if (filter?.productId) pallets = pallets.filter((pallet) => pallet.productId === filter.productId);
    if (filter?.from || filter?.to) {
      pallets = pallets.filter((pallet) => inRange(pallet.createdAt, filter.from, filter.to));
    }

    if (filter?.lineId) {
      const lineBatchIds = new Set(
        getDb()
          .batches.filter((batch) => batch.lineId === filter.lineId)
          .map((batch) => batch.id),
      );
      pallets = pallets.filter((pallet) => lineBatchIds.has(pallet.batchId));
    }

    pallets.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
    if (filter?.limit && filter.limit > 0) pallets = pallets.slice(0, filter.limit);
    return pallets;
  }

  async insertPalletWithAwards(payload: PalletWithAwards): Promise<PalletLog> {
    return mutate((db) => {
      db.palletLogs.push(payload.pallet);
      db.pointAwards.push(...payload.awards);
      return clone(payload.pallet);
    });
  }

  async deletePalletLog(id: string): Promise<void> {
    await mutate((db) => {
      db.palletLogs = db.palletLogs.filter((pallet) => pallet.id !== id);
      db.pointAwards = db.pointAwards.filter((award) => award.palletLogId !== id);
    });
  }

  async deletePalletLogsByBatch(batchId: string): Promise<void> {
    await mutate((db) => {
      db.palletLogs = db.palletLogs.filter((pallet) => pallet.batchId !== batchId);
      db.pointAwards = db.pointAwards.filter((award) => award.batchId !== batchId);
    });
  }

  /* -------------------------------------------------------- point awards */

  async listPointAwardsByBatch(batchId: string): Promise<PointAward[]> {
    return clone(getDb().pointAwards.filter((award) => award.batchId === batchId));
  }

  async listPointAwardsForBatches(batchIds: string[]): Promise<PointAward[]> {
    const set = new Set(batchIds);
    return clone(getDb().pointAwards.filter((award) => set.has(award.batchId)));
  }

  async listPointAwards(filter?: PointAwardFilter): Promise<PointAward[]> {
    let awards = clone(getDb().pointAwards);
    if (filter?.raceId) awards = awards.filter((award) => award.raceId === filter.raceId);
    if (filter?.from || filter?.to) {
      awards = awards.filter((award) => inRange(award.createdAt, filter.from, filter.to));
    }
    awards.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
    if (filter?.limit && filter.limit > 0) awards = awards.slice(0, filter.limit);
    return awards;
  }

  /* ----------------------------------------------------------- pause logs */

  async listPauseLogsByBatch(batchId: string): Promise<PauseLog[]> {
    return clone(
      getDb()
        .pauseLogs.filter((pause) => pause.batchId === batchId)
        .sort((a, b) => new Date(a.startedAt).getTime() - new Date(b.startedAt).getTime()),
    );
  }

  async listPauseLogsForBatches(batchIds: string[]): Promise<PauseLog[]> {
    const set = new Set(batchIds);
    return clone(getDb().pauseLogs.filter((pause) => set.has(pause.batchId)));
  }

  async getOpenPause(batchId: string): Promise<PauseLog | null> {
    return clone(
      getDb().pauseLogs.find((pause) => pause.batchId === batchId && pause.endedAt === null) ?? null,
    );
  }

  async insertPauseLog(pause: PauseLog): Promise<PauseLog> {
    return mutate((db) => {
      db.pauseLogs.push(pause);
      return clone(pause);
    });
  }

  async updatePauseLog(id: string, patch: Partial<Omit<PauseLog, 'id' | 'batchId'>>): Promise<PauseLog> {
    return mutate((db) => {
      const index = db.pauseLogs.findIndex((pause) => pause.id === id);
      if (index === -1) throw new RepositoryError('not_found', 'Pause log not found', 404);
      db.pauseLogs[index] = { ...db.pauseLogs[index], ...patch, id };
      return clone(db.pauseLogs[index]);
    });
  }

  async listPauseLogsInRange(from: string, to: string): Promise<PauseLog[]> {
    return clone(getDb().pauseLogs.filter((pause) => inRange(pause.startedAt, from, to)));
  }

  /* ------------------------------------------------------------ settings */

  async listSettings(): Promise<AppSetting[]> {
    return clone(getDb().appSettings);
  }

  async getSetting(key: string): Promise<string | null> {
    return getDb().appSettings.find((setting) => setting.key === key)?.value ?? null;
  }

  async setSetting(key: string, value: string): Promise<AppSetting> {
    return mutate((db) => {
      const index = db.appSettings.findIndex((setting) => setting.key === key);
      const record: AppSetting = { key, value, updatedAt: nowIso() };
      if (index === -1) db.appSettings.push(record);
      else db.appSettings[index] = record;
      return clone(record);
    });
  }

  /* ------------------------------------------------------------ bulk ops */

  async truncateAll(): Promise<void> {
    await mutate((db) => {
      Object.assign(db, emptyDatabase());
    });
  }

  /**
   * Replaces the whole document. Used by the seed script so a single call
   * produces a fully populated, consistent dataset.
   */
  async replaceAll(next: Partial<LocalDatabaseShape>): Promise<void> {
    await mutate((db) => {
      Object.assign(db, emptyDatabase(), next, { version: SCHEMA_VERSION });
    });
  }

  /** Reads the raw document — used by diagnostics and the seed script. */
  async snapshot(): Promise<LocalDatabaseShape> {
    return clone(getDb());
  }
}
